#!/usr/bin/env python3
"""Generate ``dsor/effects.py`` from the client's own status effect templates.

    python3 tools/effect_table.py ~/dso/db/db_static.sqlite > dsor/effects.py

A skill's effect list names effects; ``_Template_StatusEffect`` says what each one
does. The grammar of both is small and regular:

    UserStatusEffects   skill_warshout_buff_movementspeed,C:1.0,D:10.0,DP:10.0,$0:0.4;
    StartModifiers      Speed:$0,relative,Movement;

So "furious battlecry" -- warshout -- gives 60% of the resource through the skill's own
ResourceGain, then +40% movement speed and +30% damage through two effects. None of it
was served: this server logged "whose effect this server does not model" and stopped.

The table is filtered to the effects the five character classes' skills actually
reference, because the whole thing is 6703 rows.
"""

import re
import sqlite3
import sys

HEADER_COMMENT = (
    "#: What each class skill grants its user, and inflicts on its victim, by\n"
    "#: the skill's wire index. Only the class skills: the strings are long."
)

FIELDS = [
    "Id", "StatusEffectDuration", "StatusEffectTickRate", "MaxStackSize",
    "StartModifiers", "TickModifiers", "StopModifiers", "DoneModifiers",
    "ExclusiveGroup", "Groups",
]


def referenced(db) -> set[str]:
    """Every effect named by any class skill's three effect lists."""
    names: set[str] = set()
    rows = db.execute(
        "SELECT VictimStatusEffects, UserStatusEffects, LocationStatusEffects"
        " FROM _Template_Skill WHERE CharClass <> ''"
    )
    for row in rows:
        for cell in row:
            for entry in (cell or "").split(";"):
                head = entry.split(",")[0].strip()
                if head:
                    names.add(head)
    return names


def main(path: str) -> None:
    db = sqlite3.connect(path)
    wanted = referenced(db)
    # Plus the one this server already replays every tick, so the decoder has a
    # sample it can be checked against.
    wanted.add("a0001_tutorial_heal_on_low_health")

    rows = [
        row
        for row in db.execute(
            f"SELECT rowid - 1, {', '.join(FIELDS)} FROM _Template_StatusEffect"
            " ORDER BY rowid"
        )
        if row[1] in wanted
    ]

    def num(v, d=0.0):
        return d if v is None else round(float(v), 4)

    def whole(v, d=0):
        return d if v is None else int(v)

    def text(v):
        return "" if v is None else str(v)

    print(f'''"""What each status effect does, from the client's own template table.

Generated by ``tools/effect_table.py``; do not edit by hand.

A skill names its effects and the effect says what it changes. Both grammars are
small and regular, and both are parsed here rather than being pattern-matched at the
point of use:

    warshout's UserStatusEffects
        skill_warshout_buff_movementspeed,C:1.0,D:10.0,DP:10.0,$0:0.4;
        skill_warshout_buff_damage,C:1.0,D:10.0,DP:10.0,$0:0.3;

    skill_warshout_buff_movementspeed's StartModifiers
        Speed:$0,relative,Movement;

So "furious battlecry" is ``warshout``, and it gives 60% of the resource through the
skill's own ResourceGain plus 40% movement speed and 30% damage through those two
effects. This server modelled none of it and said so in the log.

{len(rows)} effects, of the table's 6703: those the five classes' skills reference.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from functools import cached_property


#: How an effect entry in a skill's list is written: the effect id, then keyed
#: fields, then the numbered parameters the modifiers substitute.
#:
#:   C   chance. 1.0 is unconditional; 0.0 marks the entries that need an item or a
#:       talent the character does not have, which is most of them.
#:   D   duration in seconds, DP the duration in player-versus-player.
#:   TR  a flag whose meaning is not established.
#:   ON  the trigger: Immediate, HitCritical, SkillStart, kill, LOWHEALTH.
#:   $n  the parameters, substituted into the modifiers' $0, $1, $2.
ENTRY_KEYS = ("C", "D", "DP", "TR", "DE", "OZ", "ON")


@dataclass(frozen=True)
class Modifier:
    """One change an effect makes: ``Speed:$0,relative,Movement``."""

    #: What is changed: Speed, Damage, Resistance, SkillDamage, ResourceCost,
    #: LifeLeech, ActorStatusEffect, StopStatusEffect.
    attribute: str
    #: The parameter reference, ``$0``, or a literal value.
    value: str
    #: ``relative`` (a fraction of the base) or ``absolute``.
    mode: str
    #: What it applies to: a damage type, a skill id, Movement, Min and Max.
    targets: tuple[str, ...]

    def amount(self, parameters: dict[str, float]) -> float | None:
        """The modifier's value with *parameters* substituted, or None if unknown."""
        if self.value.startswith("$"):
            return parameters.get(self.value)
        try:
            return float(self.value)
        except ValueError:
            return None


def parse_modifiers(packed: str) -> tuple[Modifier, ...]:
    """Read a StartModifiers / TickModifiers / StopModifiers string."""
    out = []
    for clause in packed.split(";"):
        clause = clause.strip()
        if not clause or ":" not in clause:
            continue
        attribute, _, rest = clause.partition(":")
        parts = [p.strip() for p in rest.split(",") if p.strip()]
        if not parts:
            continue
        value = parts[0]
        mode = parts[1] if len(parts) > 1 else ""
        targets = tuple(parts[2:]) if len(parts) > 2 else ()
        if mode not in ("relative", "absolute"):
            # Not a value-and-mode clause -- ActorStatusEffect:addAE,other_effect,...
            # keeps its whole tail as targets so nothing is silently dropped.
            targets = tuple(parts[1:])
            mode = ""
        out.append(Modifier(attribute.strip(), value, mode, targets))
    return tuple(out)


@dataclass(frozen=True)
class Entry:
    """One effect as a skill names it, with the parameters that skill supplies."""

    effect: str
    chance: float
    duration: float
    duration_pvp: float
    trigger: str
    parameters: tuple[tuple[str, float], ...]

    @property
    def certain(self) -> bool:
        """Whether the effect applies unconditionally.

        A chance of 0.0 does not mean "never" -- it marks the entries that need an
        item, a talent or a set bonus the character does not have. Most of a skill's
        list is those, which is why warshout names sixteen effects and grants three.
        """
        return self.chance >= 1.0

    @property
    def substitutions(self) -> dict[str, float]:
        return dict(self.parameters)


def parse_entries(packed: str) -> tuple[Entry, ...]:
    """Read a skill's VictimStatusEffects / UserStatusEffects / Location list."""
    out = []
    for clause in (packed or "").split(";"):
        clause = clause.strip()
        if not clause:
            continue
        parts = [p.strip() for p in clause.split(",") if p.strip()]
        if not parts:
            continue
        keyed: dict[str, str] = {{}}
        params: list[tuple[str, float]] = []
        for part in parts[1:]:
            key, _, value = part.partition(":")
            key = key.strip()
            if key.startswith("$"):
                try:
                    params.append((key, float(value)))
                except ValueError:
                    pass
            else:
                keyed[key.upper()] = value.strip()

        def number(key, default=0.0):
            try:
                return float(keyed.get(key, default))
            except ValueError:
                return default

        out.append(
            Entry(
                effect=parts[0],
                chance=number("C"),
                duration=number("D"),
                duration_pvp=number("DP"),
                trigger=keyed.get("ON", ""),
                parameters=tuple(params),
            )
        )
    return tuple(out)


@dataclass(frozen=True)
class Effect:
    """One row of the client's status effect table."""

    #: The wire index: the row before its row, the same convention as a skill's.
    #: Confirmed by decoding the 0x004F this server already replays, whose single
    #: effect reads 1350 and is row 1351, ``a0001_tutorial_heal_on_low_health`` --
    #: which is exactly what a tutorial dungeon would carry.
    wire: int
    id: str
    duration: float
    tick_rate: float
    max_stack: int
    start_modifiers: str
    tick_modifiers: str
    stop_modifiers: str
    done_modifiers: str
    exclusive_group: str
    groups: str

    @cached_property
    def starts(self) -> tuple[Modifier, ...]:
        return parse_modifiers(self.start_modifiers)

    @cached_property
    def ticks(self) -> tuple[Modifier, ...]:
        return parse_modifiers(self.tick_modifiers)

    @property
    def changes_anything(self) -> bool:
        return bool(self.starts or self.ticks)


#: Every effect the classes' skills name, by wire index.
EFFECTS: dict[int, Effect] = {{}}''')

    print()
    print("for _row in [")
    for row in rows:
        (wire, eid, duration, rate, stack, start, tick, stop, done, excl, groups) = row
        print(
            f"    ({wire}, {text(eid)!r}, {num(duration)!r}, {num(rate)!r},"
            f" {whole(stack)}, {text(start)!r}, {text(tick)!r}, {text(stop)!r},"
            f" {text(done)!r}, {text(excl)!r}, {text(groups)!r}),"
        )
    print("]:")
    print("    EFFECTS[_row[0]] = Effect(*_row)")
    print("del _row")

    # Which effects each class skill grants, by the skill wire index. Kept here
    # rather than in dsor/skills.py because the strings are long -- one of
    # battlecry's is two kilobytes -- and only the class skills need them.
    grants = db.execute(
        "SELECT rowid - 1, Id, UserStatusEffects, VictimStatusEffects"
        " FROM _Template_Skill WHERE CharClass <> '' ORDER BY rowid"
    ).fetchall()
    print()
    print(HEADER_COMMENT)
    print("SKILL_EFFECTS: dict[int, tuple[str, str]] = {")
    for wire, sid, user, victim in grants:
        print(f"    {wire}: ({text(user)!r}, {text(victim)!r}),  # {sid}")
    print("}")
    print('''

#: Every effect by template id.
BY_ID: dict[str, Effect] = {e.id: e for e in EFFECTS.values()}


def effect(wire: int | None) -> Effect | None:
    return None if wire is None else EFFECTS.get(wire)


def by_id(name: str) -> Effect | None:
    return BY_ID.get(name)


def wire_of(name: str) -> int | None:
    found = BY_ID.get(name)
    return None if found is None else found.wire


def granted_by(skill_wire: int) -> tuple[Entry, ...]:
    """The effects the skill at *skill_wire* puts on its user.

    Only the ones that apply unconditionally and actually change something. A
    skill's list is mostly entries with a chance of 0.0 -- item procs, talents,
    set bonuses -- so warshout names sixteen effects and grants three.
    """
    return _certain(SKILL_EFFECTS.get(skill_wire), 0)


def inflicted_by(skill_wire: int) -> tuple[Entry, ...]:
    """The effects the skill at *skill_wire* puts on its victims."""
    return _certain(SKILL_EFFECTS.get(skill_wire), 1)


def _certain(packed: tuple[str, str] | None, which: int) -> tuple[Entry, ...]:
    if packed is None:
        return ()
    out = []
    for entry in parse_entries(packed[which]):
        if not entry.certain:
            continue
        found = BY_ID.get(entry.effect)
        if found is None or not found.changes_anything:
            continue
        out.append(entry)
    return tuple(out)''')


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "db_static.sqlite")
