#!/usr/bin/env python3
"""Generate ``dsor/effects.py`` from the client's own status effect templates.

    python3 tools/effect_table.py ~/dso/db/db_static.sqlite > dsor/effects.py

A skill's effect list names effects; ``_Template_StatusEffect`` says what each one
does. The grammar of both is small and regular:

    UserStatusEffects   skill_warshout_buff_movementspeed,C:1.0,D:10.0,DP:10.0,$0:0.4;
    StartModifiers      Speed:$0,relative,Movement;

So "furious battlecry" -- warshout -- gives 60% of the resource through the skill's own
ResourceGain, then +40% movement speed and +30% damage through two effects. None of it
was served: this server logged "whose effect this server does not model" and stopped.

The table is filtered to the effects the five character classes' skills actually
reference, because the whole thing is 6703 rows.
"""

import re
import pathlib
import sqlite3
import sys

HEADER_COMMENT = (
    "#: What each class skill grants its user, and inflicts on its victim, by\n"
    "#: the skill's wire index. Only the class skills: the strings are long."
)

FIELDS = [
    "Id", "StatusEffectDuration", "StatusEffectTickRate", "MaxStackSize",
    "StartModifiers", "TickModifiers", "StopModifiers", "DoneModifiers",
    "ExclusiveGroup", "Groups", "StartSequence", "TickSequence", "StartAnimation",
    # The aura columns, without which a location effect is an empty container. Every
    # aura this project needed carries no modifiers of its own: skill_earthquake_aura
    # has none, and what it does lives in AuraEffectId -- a *semicolon-separated
    # list* of the effects it puts on whatever stands inside it. Reading the aura and
    # stopping there is why earthquake and defiance looked like effects that did
    # nothing: the crater's stun is skill_earthquake_shockwave_aura's AuraEffectId,
    # and Dragon Hide's free skills are skill_defiance_buff_creators_aura's.
    "AuraEffectId", "AuraRadius", "AuraTargets",
]



def connect(path: str):
    """Open the client's database read-only, and refuse a path that is not one.

    ``sqlite3.connect`` *creates* a database when the file is missing, so running one
    of these from the wrong directory left an empty ``db_static.sqlite`` behind and
    then generated a table with nothing in it. A generator that quietly produces an
    empty module is the same failure as a config file that quietly ignores a key.
    """
    found = pathlib.Path(path)
    if not found.exists():
        raise SystemExit(
            f"no database at {found}. Point this at the client's own, usually "
            "~/dso/db/db_static.sqlite"
        )
    return sqlite3.connect(f"file:{found}?mode=ro", uri=True)


def referenced(db) -> set[str]:
    """Every effect named by any class skill's three effect lists."""
    names: set[str] = set()
    rows = db.execute(
        "SELECT VictimStatusEffects, UserStatusEffects, LocationStatusEffects"
        " FROM _Template_Skill WHERE CharClass <> ''"
    )
    for row in rows:
        for cell in row:
            for entry in (cell or "").split(";"):
                head = entry.split(",")[0].strip()
                if head:
                    names.add(head)

    # And whatever those reach through their auras, transitively. An aura carries no
    # modifiers of its own -- its work is the effects named in AuraEffectId -- and
    # those leaves are named by no skill, so stopping at the skills' own lists left
    # skill_earthquake_dmg, skill_earthquake_shockwave_dmg and Dragon Hide's two
    # resource effects out of the table entirely. Every one of them is the whole of
    # what its skill actually does.
    chain = dict(
        (row[0], row[1] or "")
        for row in db.execute("SELECT Id, AuraEffectId FROM _Template_StatusEffect")
    )
    frontier = set(names)
    while frontier:
        reached = set()
        for name in frontier:
            for leaf in chain.get(name, "").split(";"):
                leaf = leaf.strip()
                if leaf and leaf not in names:
                    reached.add(leaf)
        names |= reached
        frontier = reached
    return names


def main(path: str) -> None:
    db = connect(path)
    wanted = referenced(db)
    # Plus the one this server already replays every tick, so the decoder has a
    # sample it can be checked against.
    wanted.add("a0001_tutorial_heal_on_low_health")

    rows = [
        row
        for row in db.execute(
            f"SELECT rowid - 1, {', '.join(FIELDS)} FROM _Template_StatusEffect"
            " ORDER BY rowid"
        )
        if row[1] in wanted
    ]

    def num(v, d=0.0):
        return d if v is None else round(float(v), 4)

    def whole(v, d=0):
        return d if v is None else int(v)

    def text(v):
        return "" if v is None else str(v)

    print(f'''"""What each status effect does, from the client's own template table.

Generated by ``tools/effect_table.py``; do not edit by hand.

A skill names its effects and the effect says what it changes. Both grammars are
small and regular, and both are parsed here rather than being pattern-matched at the
point of use:

    warshout's UserStatusEffects
        skill_warshout_buff_movementspeed,C:1.0,D:10.0,DP:10.0,$0:0.4;
        skill_warshout_buff_damage,C:1.0,D:10.0,DP:10.0,$0:0.3;

    skill_warshout_buff_movementspeed's StartModifiers
        Speed:$0,relative,Movement;

So "furious battlecry" is ``warshout``, and it gives 60% of the resource through the
skill's own ResourceGain plus 40% movement speed and 30% damage through those two
effects. This server modelled none of it and said so in the log.

{len(rows)} effects, of the table's 6703: those the five classes' skills reference.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from functools import cached_property


#: How an effect entry in a skill's list is written: the effect id, then keyed
#: fields, then the numbered parameters the modifiers substitute.
#:
#:   C   chance. 1.0 is unconditional; 0.0 marks the entries that need an item or a
#:       talent the character does not have, which is most of them.
#:   D   duration in seconds, DP the duration in player-versus-player.
#:   TR  a flag whose meaning is not established.
#:   ON  the trigger: Immediate, HitCritical, SkillStart, kill, LOWHEALTH.
#:   $n  the parameters, substituted into the modifiers' $0, $1, $2.
ENTRY_KEYS = ("C", "D", "DP", "TR", "DE", "OZ", "ON")


@dataclass(frozen=True)
class Modifier:
    """One change an effect makes: ``Speed:$0,relative,Movement``."""

    #: What is changed: Speed, Damage, Resistance, SkillDamage, ResourceCost,
    #: LifeLeech, ActorStatusEffect, StopStatusEffect.
    attribute: str
    #: The parameter reference, ``$0``, or a literal value.
    value: str
    #: ``relative`` (a fraction of the base) or ``absolute``.
    mode: str
    #: What it applies to: a damage type, a skill id, Movement, Min and Max.
    targets: tuple[str, ...]

    @property
    def skills_named(self) -> tuple[str, ...]:
        """The skill ids this modifier names, if it names any.

        A target can carry a suffix -- ``angrystrike#skillDamageRel`` -- which is
        stripped, because the part before the hash is the template id.
        """
        if self.attribute not in SKILL_ATTRIBUTES:
            return ()
        return tuple(target.split("#")[0] for target in self.targets)

    def amount(self, parameters: dict[str, float]) -> float | None:
        """The modifier's value with *parameters* substituted, or None if unknown."""
        if self.value.startswith("$"):
            return parameters.get(self.value)
        try:
            return float(self.value)
        except ValueError:
            return None


#: Modifier attributes that reach into a *skill's* definition, or spawn an actor.
#: Serving one asks the client to resolve something the character does not own, and it
#: asserts rather than shrug: ``skillTemplateId.IsValid()`` in
#: Game::ActorStatusEffectModule, reached through GetSkillLocaAddModifications.
#:
#: The two that produced it are identifiable:
#:
#:   set_cny2026_warrior_earthquake_dmg
#:       SkillStatusEffect:modLE,earthquake,skill_earthquake_aura,$1:-0.05
#:   warrior_talent_damage_dealer_cooldown_reduction
#:       ActiveCoolDown:$talent_warrior_dd_cd,absolute,Skill01..Skill20
#:
#: One rewrites another skill's status effects, the other names skill *slots*. Both go
#: through the skill-template path, and neither belongs on a character with no set and
#: no talents.
FORBIDDEN_ATTRIBUTES = frozenset({
    "SkillStatusEffect", "ActiveCoolDown", "Localize", "SkillSequence",
    "UnlockHiddenSkills", "SkinModifier", "Minion", "Pet", "Mounted",
    "DropAmount",
    # A capture-the-flag flag, from warshout's ctfdropflag. Not in the tooltip, and
    # nothing to do with a dungeon.
    "PVPEventModifier",
})

#: Modifier attributes that name a skill. Safe only when every skill they name is one
#: the character actually has -- which keeps warshout's angrystrike buff and
#: frenzyshout's life leech, both of which name warrior skills a level 100 warrior has.
SKILL_ATTRIBUTES = frozenset({
    "SkillDamage", "SkillHitDamage", "LifeLeech", "ResourceCost", "CoolDown",
    "SkillDamageType",
})

#: Effect ids this server will force when asked. A skill's own effects and the
#: crowd-control and damage-over-time debuffs, and nothing that depends on equipment,
#: a set or a talent -- because forcing those is both nonsense on a character who has
#: none and the road to the assertion above.
FORCEABLE_PREFIXES = ("skill_", "debuff_", "buff_")


def forceable(effect_id: str) -> bool:
    """Whether *effect_id* is one this server will force."""
    return effect_id.startswith(FORCEABLE_PREFIXES)


def parse_modifiers(packed: str) -> tuple[Modifier, ...]:
    """Read a StartModifiers / TickModifiers / StopModifiers string."""
    out = []
    for clause in packed.split(";"):
        clause = clause.strip()
        if not clause:
            continue
        if ":" not in clause:
            # A bare word is a flag with no value: skill_mighty360_debuff_taunt's
            # whole StartModifiers is "Taunt". Dropping those made the effect look
            # like it changed nothing, and the tool that checks tooltips against what
            # is served then blamed the wrong thing.
            out.append(Modifier(clause, "", "", ()))
            continue
        attribute, _, rest = clause.partition(":")
        parts = [p.strip() for p in rest.split(",") if p.strip()]
        if not parts:
            continue
        value = parts[0]
        mode = parts[1] if len(parts) > 1 else ""
        targets = tuple(parts[2:]) if len(parts) > 2 else ()
        if mode not in ("relative", "absolute"):
            # Not a value-and-mode clause -- ActorStatusEffect:addAE,other_effect,...
            # keeps its whole tail as targets so nothing is silently dropped.
            targets = tuple(parts[1:])
            mode = ""
        out.append(Modifier(attribute.strip(), value, mode, targets))
    return tuple(out)


@dataclass(frozen=True)
class Entry:
    """One effect as a skill names it, with the parameters that skill supplies."""

    effect: str
    chance: float
    duration: float
    duration_pvp: float
    trigger: str
    parameters: tuple[tuple[str, float], ...]

    @property
    def certain(self) -> bool:
        """Whether the effect applies unconditionally.

        A chance of 0.0 does not mean "never" -- it marks the entries that need an
        item, a talent or a set bonus the character does not have. Most of a skill's
        list is those, which is why warshout names sixteen effects and grants three.
        """
        return self.chance >= 1.0

    @property
    def substitutions(self) -> dict[str, float]:
        return dict(self.parameters)


def parse_entries(packed: str) -> tuple[Entry, ...]:
    """Read a skill's VictimStatusEffects / UserStatusEffects / Location list."""
    out = []
    for clause in (packed or "").split(";"):
        clause = clause.strip()
        if not clause:
            continue
        parts = [p.strip() for p in clause.split(",") if p.strip()]
        if not parts:
            continue
        keyed: dict[str, str] = {{}}
        params: list[tuple[str, float]] = []
        for part in parts[1:]:
            key, _, value = part.partition(":")
            key = key.strip()
            if key.startswith("$"):
                try:
                    params.append((key, float(value)))
                except ValueError:
                    pass
            else:
                keyed[key.upper()] = value.strip()

        def number(key, default=0.0):
            try:
                return float(keyed.get(key, default))
            except ValueError:
                return default

        out.append(
            Entry(
                effect=parts[0],
                chance=number("C"),
                duration=number("D"),
                duration_pvp=number("DP"),
                trigger=keyed.get("ON", ""),
                parameters=tuple(params),
            )
        )
    return tuple(out)


@dataclass(frozen=True)
class Effect:
    """One row of the client's status effect table."""

    #: The wire index: the row before its row, the same convention as a skill's.
    #: Confirmed by decoding the 0x004F this server already replays, whose single
    #: effect reads 1350 and is row 1351, ``a0001_tutorial_heal_on_low_health`` --
    #: which is exactly what a tutorial dungeon would carry.
    wire: int
    id: str
    duration: float
    tick_rate: float
    max_stack: int
    start_modifiers: str
    tick_modifiers: str
    stop_modifiers: str
    done_modifiers: str
    exclusive_group: str
    groups: str
    #: The animation the client plays for this effect, and the reason the sequencer
    #: field matters: a0001_tutorial_heal_on_low_health has none, so the recording
    #: never exercised that path, and every effect worth sending does have one.
    start_sequence: str
    tick_sequence: str
    start_animation: str
    #: The effects this aura puts on whatever stands inside it, as the column holds
    #: them: a semicolon-separated list of effect ids. See :attr:`aura_effects`.
    aura_effect_ids: str = ""
    #: How wide the aura reaches, in world units. 2.15 for earthquake's own aura,
    #: 3.0 for its shockwave, 5.75 for Dragon Hide.
    aura_radius: float = 0.0
    #: Who it reaches: Creator, Enemies, Allies.
    aura_targets: str = ""

    @property
    def aura_effects(self) -> tuple[str, ...]:
        """The ids in :attr:`aura_effect_ids`, split.

        A single-value column that is sometimes a list is exactly the shape that gets
        read as one name and found missing: looking up the whole of
        ``"skill_earthquake_dmg;skill_earthquake_debuff_movementspeed"`` finds
        nothing, and nothing is what earthquake did.
        """
        return tuple(
            part.strip() for part in self.aura_effect_ids.split(";") if part.strip()
        )

    @cached_property
    def starts(self) -> tuple[Modifier, ...]:
        return parse_modifiers(self.start_modifiers)

    @cached_property
    def ticks(self) -> tuple[Modifier, ...]:
        return parse_modifiers(self.tick_modifiers)

    @property
    def changes_anything(self) -> bool:
        return bool(self.starts or self.ticks)

    @property
    def over_time(self) -> bool:
        """Whether the effect deals damage on a tick rather than at once.

        debuff_dot_poison, debuff_dot_burn and debuff_dot_bleeding all carry
        ``CurrHealthPointsDmg`` in TickModifiers. The client would do this itself given
        the effect, but every one of them is animated and an animated effect cannot be
        sent yet -- so the damage is served and the green bubbles are not.
        """
        return any(
            modifier.attribute == "CurrHealthPointsDmg" for modifier in self.ticks
        )

    @property
    def animated(self) -> bool:
        """Whether the client plays a sequence or an animation for this effect.

        The recorded element this server copies belongs to
        a0001_tutorial_heal_on_low_health, which has none of the three -- so replaying
        it never entered the sequencer, and the vectors in the element's tail were
        never used. An animated effect does enter it, with a tail copied from an effect
        that had no tracks and no position for them, and the client asserts:

            Util::FixedArray<Core::Ptr<Sequencer::TrackSequencer>>::operator[](int)

        Zeroing the field that looked like a track index made it worse, because that
        field is a length discriminator -- see dsor/recorded.py. So an animated effect
        is held back until the tail is understood, rather than sent and crashed on.
        """
        return bool(self.start_sequence or self.tick_sequence or self.start_animation)

    def servable(self, known_skills: frozenset[str] = frozenset()) -> bool:
        """Whether every modifier is one this server can serve.

        Permissive by default and strict where it has to be. A modifier that only
        changes a number on the actor, chains another effect or sets a variable is
        fine. One that names a skill is fine when the character has every skill it
        names. One in :data:`FORBIDDEN_ATTRIBUTES` never is, because it reaches into a
        skill's own definition or spawns an actor, and the client asserts rather than
        shrug.

        Being permissive matters: a strict "plain attributes only" rule threw out
        debuff_cc_stun for carrying a StopStatusEffect and debuff_dot_poison for
        chaining an explosion trigger -- the two effects most worth having.
        """
        modifiers = self.starts + self.ticks
        if not modifiers:
            return False
        for modifier in modifiers:
            if modifier.attribute in FORBIDDEN_ATTRIBUTES:
                return False
            named = modifier.skills_named
            if named and not all(skill in known_skills for skill in named):
                return False
        return True


#: Every effect the classes' skills name, by wire index.
EFFECTS: dict[int, Effect] = {{}}''')

    print()
    print("for _row in [")
    for row in rows:
        (wire, eid, duration, rate, stack, start, tick, stop, done, excl, groups,
         start_seq, tick_seq, start_anim, aura_ids, aura_radius, aura_targets) = row
        print(
            f"    ({wire}, {text(eid)!r}, {num(duration)!r}, {num(rate)!r},"
            f" {whole(stack)}, {text(start)!r}, {text(tick)!r}, {text(stop)!r},"
            f" {text(done)!r}, {text(excl)!r}, {text(groups)!r},"
            f" {text(start_seq)!r}, {text(tick_seq)!r}, {text(start_anim)!r},"
            f" {text(aura_ids)!r}, {num(aura_radius)!r}, {text(aura_targets)!r}),"
        )
    print("]:")
    print("    EFFECTS[_row[0]] = Effect(*_row)")
    print("del _row")

    # Which effects each class skill grants, by the skill wire index. Kept here
    # rather than in dsor/skills.py because the strings are long -- one of
    # battlecry's is two kilobytes -- and only the class skills need them.
    grants = db.execute(
        "SELECT rowid - 1, Id, UserStatusEffects, VictimStatusEffects"
        " FROM _Template_Skill WHERE CharClass <> '' ORDER BY rowid"
    ).fetchall()
    print()
    print(HEADER_COMMENT)
    print("SKILL_EFFECTS: dict[int, tuple[str, str]] = {")
    for wire, sid, user, victim in grants:
        print(f"    {wire}: ({text(user)!r}, {text(victim)!r}),  # {sid}")
    print("}")

    # And the third list, which no earlier version of this table carried. A skill's
    # LocationStatusEffects is what it lays on the ground: earthquake's crater and
    # Dragon Hide's are both entirely here, which is why both looked inert.
    places = db.execute(
        "SELECT rowid - 1, Id, LocationStatusEffects"
        " FROM _Template_Skill WHERE CharClass <> '' AND LocationStatusEffects <> ''"
        " ORDER BY rowid"
    ).fetchall()
    print()
    print("#: What each class skill lays on the ground, by skill wire index.")
    print("SKILL_LOCATIONS: dict[int, str] = {")
    for wire, sid, where in places:
        print(f"    {wire}: {text(where)!r},  # {sid}")
    print("}")

    # What each skill's own tooltip says it does.
    #
    # This is the authority, and the C: field is not. A skill's effect list carries a
    # chance that reads like one and is not: seismicslam's armour break, which its
    # description names, is C:0.0, while the debuff_cc_stun it does *not* name is C:1.0
    # -- and laceratingstrike is the other way round. Filtering on C therefore served
    # the stun that is not promised and dropped the armour break that is, which is
    # exactly the inversion that was reported twice.
    #
    # _Template_LocaleToken says which effect each piece of a description reads from,
    # so a token of type SkillEffect names an effect the skill advertises. UserEffect
    # goes on the caster, VictimEffect on what it hits, LocationEffect on the ground --
    # and that last one cannot be served at all without NewLocationEffectCommand.
    tokens = db.execute(
        "SELECT DISTINCT Param1Id, Param1Attr, Param2Id FROM _Template_LocaleToken"
        " WHERE TokenType = 'SkillEffect' AND Param1Id <> '' AND Param2Id <> ''"
    ).fetchall()
    by_skill: dict[str, set] = {}
    for skill, kind, effect_id in tokens:
        by_skill.setdefault(skill, set()).add((kind, effect_id))
    wire_of_skill = {
        row[1]: row[0]
        for row in db.execute("SELECT rowid - 1, Id FROM _Template_Skill")
    }
    print()
    print("#: What each skill's tooltip says it does: (kind, effect id) per skill wire")
    print("#: index. UserEffect on the caster, VictimEffect on the victim,")
    print("#: LocationEffect on the ground. The authority on which effects a skill has.")
    print("PROMISED: dict[int, tuple[tuple[str, str], ...]] = {")
    for skill in sorted(by_skill):
        wire = wire_of_skill.get(skill)
        if wire is None:
            continue
        pairs = tuple(sorted(by_skill[skill]))
        print(f"    {wire}: {pairs!r},  # {skill}")
    print("}")
    print('''

#: Every effect by template id.
BY_ID: dict[str, Effect] = {e.id: e for e in EFFECTS.values()}


def effect(wire: int | None) -> Effect | None:
    return None if wire is None else EFFECTS.get(wire)


def by_id(name: str) -> Effect | None:
    return BY_ID.get(name)


def wire_of(name: str) -> int | None:
    found = BY_ID.get(name)
    return None if found is None else found.wire


def promised_by(skill_wire: int, kind: str) -> tuple[str, ...]:
    """The effect ids the skill's own tooltip names for *kind*.

    ``UserEffect``, ``VictimEffect`` or ``LocationEffect``. Empty when the skill has no
    token of that kind, which for a great many skills means it advertises no effect at
    all -- mightybash's tooltip names only a damage range, so it promises no stun.
    """
    return tuple(
        effect_id
        for token_kind, effect_id in PROMISED.get(skill_wire, ())
        if token_kind == kind
    )


def granted_by(skill_wire: int) -> tuple[Entry, ...]:
    """The effects the skill at *skill_wire* puts on its user.

    Only the ones that apply unconditionally and actually change something. A
    skill's list is mostly entries with a chance of 0.0 -- item procs, talents,
    set bonuses -- so warshout names sixteen effects and grants three.
    """
    return _certain(
        SKILL_EFFECTS.get(skill_wire), 0,
        promised=promised_by(skill_wire, "UserEffect"),
    )


def inflicted_by(skill_wire: int) -> tuple[Entry, ...]:
    """The effects the skill at *skill_wire* puts on its victims."""
    return _certain(
        SKILL_EFFECTS.get(skill_wire), 1,
        promised=promised_by(skill_wire, "VictimEffect"),
    )


def anything_by(skill_wire: int, victim: bool = False) -> tuple[Entry, ...]:
    """Every effect the skill names, chance or no chance.

    A chance of 0.0 marks the entries gated behind an item, a talent or a set bonus,
    and the warrior's stun and poison are among them: laceratingstrike's
    debuff_cc_stun and mightybash's debuff_dot_poison both read C:0.0. Faithfully they
    never fire without the talent that raises the chance, and this server has no
    talents -- so this exists to be able to exercise them, and the switch that uses it
    is off by default.
    """
    return _certain(SKILL_EFFECTS.get(skill_wire), 1 if victim else 0, gated=True)


def _certain(
    packed: tuple[str, str] | None,
    which: int,
    gated: bool = False,
    promised: tuple[str, ...] = (),
) -> tuple[Entry, ...]:
    if packed is None:
        return ()
    out = []
    for entry in parse_entries(packed[which]):
        # The union of the two statements the client makes, not one or the other.
        #
        # An entry applies if the tooltip names it *or* its chance is 1.0. Both are
        # the client's own words about the same skill and they cover different
        # ground: the tooltip names effects whose C: reads 0.0 (Ground Breaker's
        # armour break, Rageful Swing's damage debuff), and C:1.0 marks effects the
        # tooltip does not bother to mention (Ground Breaker's *stun*, Bloody Wild
        # Swing's bleed, Charge's stun).
        #
        # Making the tooltip the sole authority was a half-fix that then subtracted.
        # It was introduced to stop C: being read as a chance -- which it is not --
        # and it did stop that, but it also threw away every certain effect the
        # tooltip is silent about: five of the warrior's, including the stun that is
        # the whole point of Ground Breaker. Adding on the tooltip's word is right;
        # removing on its silence is not.
        #
        # The noise this lets in is already handled downstream: ctfdropflag carries a
        # PVPEventModifier and fails servable(), and skill_battlecry_impact_visualizer
        # changes nothing and fails changes_anything.
        if not (gated or entry.certain or entry.effect in promised):
            continue
        found = BY_ID.get(entry.effect)
        if found is None or not found.changes_anything:
            continue
        out.append(entry)
    return tuple(out)''')


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "db_static.sqlite")
