#!/usr/bin/env python3
"""Generate the displayed English names of status effects into dsor/titles.py.

Why they matter for a server that never sends them: they are what the player reads, so
they are the only way to compare what went out with what appeared on the screen.

**The name is not keyed on the effect's Id.** ``_Template_StatusEffect`` has a
``LocaleId`` column, and 642 of the 6,703 effects use it -- it already carries the
``Title`` suffix, so it is the lookup key verbatim. ``skill_frenzyshout_buff_armor``
has no entry of its own; its LocaleId is ``warrior_frenzyshout_buff_armorTitle``, which
reads "Dragon Hide". Looking the title up by Id said Dragon Hide's buffs were nameless
and produced a confident, wrong explanation of what the operator was seeing. The
operator settled it by casting the skill on the live service and reporting two effects
labelled "Dragon Hide", which is exactly what the LocaleId column gives.

    python3 tools/effect_titles.py
"""
from __future__ import annotations

import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import bundle  # noqa: E402

CLIENT = pathlib.Path.home() / "dso/DSOClient"
WANTED = "db.statuseffect.xml"
LANGUAGE = "/language/en/"


def main() -> int:
    held = bundle.index_all(CLIENT)
    paths = [k for k in held if LANGUAGE in k and k.endswith(WANTED)]
    if not paths:
        print(f"no {WANTED} under {CLIENT}", file=sys.stderr)
        return 1
    strings: dict[str, str] = {}
    for archive in {held[k] for k in paths}:
        keep = set(paths)
        for name, stored in bundle.read(CLIENT / archive):
            if name not in keep:
                continue
            text = bundle.unwrap(stored).decode("utf-8-sig")
            for key, value in re.findall(
                r'<item name="([^"]+)"><!\[CDATA\[(.*?)\]\]></item>', text, re.S
            ):
                flat = " ".join(value.split())
                if flat:
                    strings[key] = flat

    from dsor import database

    found: dict[str, str] = {}
    for _index, effect_id, locale_id in database.rows(
        "_Template_StatusEffect", "Id", "LocaleId"
    ):
        if not effect_id:
            continue
        # LocaleId first, verbatim -- it already ends in Title. Then the effect's own
        # id plus Title, which is how the 6,061 effects without a LocaleId are named.
        title = strings.get(locale_id or "") or strings.get(f"{effect_id}Title", "")
        if title:
            found[effect_id] = title
    out = pathlib.Path(__file__).resolve().parent.parent / "dsor/effect_titles.py"
    lines = [
        '"""The displayed English name of each status effect.',
        "",
        "Generated by tools/effect_titles.py -- do not edit by hand.",
        "",
        f"{len(found)} of the database's 6,703 effects have one, resolved through LocaleId",
        "first and the effect's own id second. The rest show no name at all.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f"TITLES: dict[str, str] = {found!r}",
        "",
        "",
        "def effect_title(effect_id: str) -> str:",
        '    """The name the client shows for *effect_id*, or "" when it shows none."""',
        "    return TITLES.get(effect_id, \"\")",
        "",
    ]
    out.write_text("\n".join(lines))
    print(f"{len(found)} titles -> {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
