#!/usr/bin/env python3
"""Extract real status effect elements from a capture, verbatim.

    python3 tools/element_table.py ~/dso-capture/session-<stamp>.jsonl > dsor/elements.py

Three attempts at building an element from scratch each got a field wrong -- the
sequencer field read as a track index, then as a stack size, then field 2 written as a
constant 25 when 185 of 365 real elements carry 50 or 75. Every one of those was a
correlation that held over the sample I happened to look at.

So this stops building them. An element is copied bit for bit from one the live service
sent for that same effect, and only the fields whose meaning is *established* are
rewritten: the three ticks and, in the message around it, the actor. Everything else
carries a value a real server sent.

The cost is honest and bounded: only the effects present in a capture can be served.
The three element lengths -- 276 bits with no parameters, 477 with parameters and no
vectors, 669 with vectors -- are exactly the three forms the grammar describes, which
is the strongest confirmation available that the grammar is right.
"""

import json
import pathlib
import sqlite3
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from raknet.datagram import parse_datagram_header  # noqa: E402
from raknet.frame import parse_frames  # noqa: E402

VECTOR_BITS = 192


class Reader:
    __slots__ = ("data", "at")

    def __init__(self, data):
        self.data, self.at = data, 0

    def bits(self, count):
        value = 0
        for _ in range(count):
            value = (value << 1) | ((self.data[self.at >> 3] >> (7 - (self.at & 7))) & 1)
            self.at += 1
        return value

    def uint(self, count):
        return int.from_bytes(bytes(self.bits(8) for _ in range(count // 8)), "little")


def elements(body):
    """Every element in a payload of chained 0x004F, as (index, first bit, bit span)."""
    reader = Reader(body)
    total = len(body) * 8
    found = []
    while True:
        reader.bits(1)
        count = reader.uint(32)
        if not 0 <= count <= 64:
            return found
        for _ in range(count):
            start = reader.at
            index = reader.uint(16)
            for _ in range(8):
                reader.uint(32)
            flags = [reader.bits(1) for _ in range(4)]
            if flags[3]:
                parameters = reader.uint(32)
                if parameters > 16:
                    return found
                for _ in range(parameters):
                    reader.uint(32)
                reader.bits(1)
                tail = reader.bits(8)
                signed = tail - 256 if tail > 127 else tail
                if signed != -1:
                    if reader.at + VECTOR_BITS > total:
                        return found
                    reader.bits(VECTOR_BITS)
            found.append((index, start, reader.at - start))
        reader.uint(32)
        if reader.bits(8) != 0xFF or total - reader.at < 24:
            return found
        if reader.uint(16) != 0x004F:
            return found


def slice_bits(body, start, span):
    """*span* bits from *start*, packed into bytes from bit zero."""
    out = bytearray((span + 7) // 8)
    for index in range(span):
        source = start + index
        if (body[source >> 3] >> (7 - (source & 7))) & 1:
            out[index >> 3] |= 1 << (7 - (index & 7))
    return bytes(out)


def main(capture: str, database: str) -> None:
    names = {
        row[0] - 1: row[1]
        for row in sqlite3.connect(f"file:{database}?mode=ro", uri=True).execute(
            "SELECT rowid, Id FROM _Template_StatusEffect"
        )
    }
    found = {}
    for line in pathlib.Path(capture).read_text(errors="ignore").splitlines():
        try:
            record = json.loads(line)
        except Exception:
            continue
        if not record.get("from_server") or "hex" not in record:
            continue
        try:
            raw = bytes.fromhex(record["hex"])
            _header, offset = parse_datagram_header(raw)
            frames = parse_frames(raw, offset)
        except Exception:
            continue
        for frame in frames:
            payload = frame.payload
            if frame.split_count is not None or len(payload) < 4:
                continue
            if payload[0] != 0x85 or payload[1:3] != (0x004F).to_bytes(2, "little"):
                continue
            body = payload[3:]
            for index, start, span in elements(body):
                found.setdefault(index, (span, slice_bits(body, start, span)))

    print(f'''"""Real status effect elements, copied bit for bit off the wire.

Generated by ``tools/element_table.py``; do not edit by hand.

Three attempts at building an element got a field wrong. The 8-bit field past the
parameters was read as a track index and then as a stack size, and field 2 was written
as a constant 25 when 185 of 365 real elements carry 50 or 75. Each was a correlation
that held over the sample I happened to look at and not over the next one.

So an element is not built. It is copied from one the live service sent for that same
effect, and only the fields whose meaning is established get rewritten: the three ticks,
and the actor in the message around it.

The cost is that only the effects a capture contains can be served -- {len(found)} of
them here. The gain is that every field this server does not understand carries a value
a real server chose.

Element lengths are 276 bits with no parameters, 477 with parameters and no vectors and
669 with vectors, which are exactly the three forms the grammar describes.
"""

from __future__ import annotations

#: Effect wire index -> (bit length, the element's bits packed from bit zero).
ELEMENTS: dict[int, tuple[int, bytes]] = {{''')
    for index in sorted(found):
        span, bits = found[index]
        print(f"    {index}: ({span}, bytes.fromhex({bits.hex()!r})),  # {names.get(index, '?')}")
    print("}")

    # A donor: the element to lend to an effect that has none of its own.
    #
    # Building one from corpus constants was the previous answer and it is weaker than
    # this. The vector-carrying form is the majority -- 93 of 119 real elements -- and
    # its constants differ from the other form's: field 2 is 75 in 58 of them where the
    # 477-bit form is unanimously 25, and fields 1 and 5 are zero in 63 of them where
    # the other form carries real ticks. Choosing between those by counting is how the
    # last three readings of these fields went wrong.
    #
    # So an effect with no element of its own borrows a real one whole. Every field this
    # server does not understand -- the vectors, field 2, the flags -- then carries a
    # value the live service actually sent, and only the index, the ticks and the
    # parameters are written.
    #
    # The one chosen is the commonest vector-carrying element in the capture.
    donors = [
        (index, span, bits)
        for index, (span, bits) in found.items()
        if span == 669
    ]
    if donors:
        index, span, bits = donors[0]
        print()
        print("#: The element lent to an effect that has none of its own. See above for")
        print(f"#: why it is borrowed rather than built. Taken from {names.get(index, '?')}.")
        print(f"DONOR: tuple[int, bytes] = ({span}, bytes.fromhex({bits.hex()!r}))")
    else:
        print()
        print("DONOR: tuple[int, bytes] | None = None")
    print('''

def element(wire: int) -> tuple[int, bytes] | None:
    """The real element for *wire*, or None if no capture contained one."""
    return ELEMENTS.get(wire)


def known() -> frozenset[int]:
    """Every effect a real element exists for."""
    return frozenset(ELEMENTS)''')


if __name__ == "__main__":
    main(
        sys.argv[1],
        sys.argv[2] if len(sys.argv) > 2 else str(pathlib.Path.home() / "dso/db/db_static.sqlite"),
    )
