"""Generate ``dsor/monsters.py`` from the client's own monster templates.

    python3 tools/monster_table.py ~/dso/db/db_static.sqlite a0001 > dsor/monsters.py

The second argument is a template-id prefix. The whole table is 7985 creatures and
1.3 MB of generated Python, so it is filtered to the maps actually served -- the same
choice ``dsor/mapdata.py`` makes, and the same consequence: serving a new map means
regenerating with its prefix added. Pass no prefix for everything.

Every creature's health, damage, armour and resistances are in ``_Template_Monster``,
and two of the numbers this server invented turn out to be in there plainly:

  a0001_gen_anderworld_creature   HitPoints 24, damage 1 to 1, Armor 625
  a0001_tutorial_movement_target  HitPoints 2,  damage 0 to 0, Name "hint monster"

This server served 12 health and 8 damage for every creature alike.
"""

import pathlib
import sqlite3
import sys

FIELDS = [
    "Id", "Name", "CharLevel", "HitPoints", "MinDamage", "MaxDamage", "Armor",
    "Resistances", "CriticalDamageFactor", "BlockDamageReduction", "RankOverride",
]



def connect(path: str):
    """Open the client's database read-only, and refuse a path that is not one.

    ``sqlite3.connect`` *creates* a database when the file is missing, so running one
    of these from the wrong directory left an empty ``db_static.sqlite`` behind and
    then generated a table with nothing in it. A generator that quietly produces an
    empty module is the same failure as a config file that quietly ignores a key.
    """
    found = pathlib.Path(path)
    if not found.exists():
        raise SystemExit(
            f"no database at {found}. Point this at the client's own, usually "
            "~/dso/db/db_static.sqlite"
        )
    return sqlite3.connect(f"file:{found}?mode=ro", uri=True)


def main(path: str, prefixes: list[str]) -> None:
    db = connect(path)
    if prefixes:
        where = " OR ".join("Id LIKE ?" for _ in prefixes)
        rows = db.execute(
            f"SELECT {', '.join(FIELDS)} FROM _Template_Monster"
            f" WHERE {where} ORDER BY Id",
            [f"{prefix}%" for prefix in prefixes],
        ).fetchall()
    else:
        rows = db.execute(
            f"SELECT {', '.join(FIELDS)} FROM _Template_Monster ORDER BY Id"
        ).fetchall()

    def num(value, default=0.0):
        return default if value is None else round(float(value), 3)

    def whole(value, default=0):
        return default if value is None else int(value)

    def text(value):
        return "" if value is None else str(value)

    print(f'''"""Every creature the client knows, from its own ``_Template_Monster`` table.

Generated by ``tools/monster_table.py``; do not edit by hand.

Two of this server's invented numbers are in here plainly, and both were wrong:

  a0001_gen_anderworld_creature   HitPoints 24, damage 1 to 1
  a0001_tutorial_movement_target  HitPoints 2,  damage 0 to 0, Name "hint monster"

Twelve health was served instead of 24, and it came from decoding a recorded blow as
"victim health 0, max 12, damage 11". The caution written beside that reading said
that misreading the field one or two bits late gives 24 -- and 24 is what the client's
own database holds. The mirage warned about was the value actually served.

It also settles an older caution properly. Serving 60 health was read by the client as
a *heal* and drawn as a floating +400, and the conclusion drawn was "serving far more
than 12 is read as a heal". The real rule is narrower and more useful: the client
knows each creature's health from this table, so a figure that disagrees with it is
read as a change to it. Serving the template's own number cannot be misread, however
large it is.

{len(rows)} creatures, of the table's 7985: those whose id begins with
{", ".join(prefixes) if prefixes else "anything"}. Serving another map means
regenerating with its prefix, the way ``dsor/mapdata.py`` is regenerated per map.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import cached_property


@dataclass(frozen=True)
class Monster:
    """One row of the client's monster table."""

    id: str
    #: The shared display name. Several ids share one: the tutorial dungeon's
    #: ordinary creature and its health-globe variant are both "anderworld_creature".
    name: str
    level: int
    hit_points: int
    #: The blow it lands, before its skill's own multiplier. One to one for the
    #: tutorial creature, zero for the practice dummy, five to nine for the champion.
    min_damage: float
    max_damage: float
    armor: float
    #: The raw ``Fire:625;Ice:625;...`` string, parsed on demand by :attr:`resists`.
    resistances: str
    critical_damage_factor: float
    block_damage_reduction: float
    rank_override: int

    @cached_property
    def resists(self) -> dict[str, float]:
        """Resistances by damage type, parsed from the packed string."""
        out: dict[str, float] = {{}}
        for part in self.resistances.split(";"):
            if ":" not in part:
                continue
            kind, _, value = part.partition(":")
            try:
                out[kind.strip()] = float(value)
            except ValueError:
                continue
        return out

    @property
    def harmless(self) -> bool:
        """Whether it deals no damage at all.

        The tutorial dungeon's movement target is one: two health, no damage, and the
        client calls it a "hint monster". It stands eight units from where a player
        arrives, and serving every creature the same blow meant it hit them
        invisibly.
        """
        return self.max_damage <= 0.0


#: Every creature, by template id.
MONSTERS: dict[str, Monster] = {{}}''')

    print()
    print("for _row in [")
    for row in rows:
        (mid, name, level, hp, lo, hi, armor, resists, crit, block, rank) = row
        print(
            f"    ({text(mid)!r}, {text(name)!r}, {whole(level)}, {whole(hp)},"
            f" {num(lo)!r}, {num(hi)!r}, {num(armor)!r}, {text(resists)!r},"
            f" {num(crit)!r}, {num(block)!r}, {whole(rank)}),"
        )
    print("]:")
    print("    MONSTERS[_row[0]] = Monster(*_row)")
    print("del _row")
    print('''

def monster(blueprint: str | None) -> Monster | None:
    """The creature *blueprint* names, or None if the table has no such row.

    ``a0001_normal_anderworld_minion_01`` is one that has none: the map's spawn table
    names it and the monster table does not carry it, so a caller must cope with None
    rather than assume every spawned blueprint is described here.
    """
    return None if blueprint is None else MONSTERS.get(blueprint)''')


if __name__ == "__main__":
    main(
        sys.argv[1] if len(sys.argv) > 1 else "db_static.sqlite",
        list(sys.argv[2:]),
    )
