#!/usr/bin/env python3
"""The true bit length of every payload this server replays.

Run as::

    python3 tools/payload_bits.py ~/dso-capture/session-*.jsonl > dsor/payload_bits.py

A frame's length field is in bits and the client reads to exactly that boundary.
``dsor/data/*.bin`` holds payload *bytes*, so a message whose real length is not a
multiple of eight came out of the file already padded and its length was lost --
after which the frame builder had nothing better than ``len * 8`` and declared up to
seven bits too many.

That is not cosmetic. A multi-command payload is decoded command after command until
the bit stream is exhausted, so spare bits at the end are read as the start of one
more command:

    DecodeCommand() invalid command ending in multi command 79!

Measured on the live service: its HitCommand frames carry a sub-byte length in 98 of
98 and its StatusEffectCommand frames in 90 of 91, while this server declared
``len * 8`` for 100% of everything it sent, replay and built alike. Messages built
with a BitWriter know their own length now; the replays need this table, because the
information is simply not in the bytes.

Each blob is looked up by exact content in the captures and its declared length
recorded. A blob that appears in no capture is left out rather than guessed at, and
the caller falls back to ``len * 8`` for it.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from raknet.datagram import parse_datagram_header  # noqa: E402
from raknet.frame import parse_frames  # noqa: E402

DATA = pathlib.Path(__file__).resolve().parent.parent / "dsor/data"


def main(argv: list[str]) -> int:
    captures = [pathlib.Path(a) for a in argv[1:] if a.endswith(".jsonl")]
    if not captures:
        captures = sorted(pathlib.Path.home().glob("dso-capture/session-*.jsonl"))
    blobs: dict[bytes, str] = {}
    for path in sorted(DATA.glob("*.bin")):
        body = path.read_bytes()
        if body:
            blobs.setdefault(body, path.name)

    found: dict[str, int] = {}
    for path in captures:
        if len(found) == len(blobs):
            break
        try:
            lines = path.read_text(errors="ignore").splitlines()
        except OSError:
            continue
        for line in lines:
            try:
                record = json.loads(line)
            except Exception:
                continue
            if "hex" not in record:
                continue
            try:
                buf = bytes.fromhex(record["hex"])
                _header, offset = parse_datagram_header(buf)
                frames = parse_frames(buf, offset)
            except Exception:
                continue
            for frame in frames:
                name = blobs.get(frame.payload)
                if name is None or name in found:
                    continue
                bits = frame.bit_length
                if bits is None:
                    continue
                found[name] = bits

    short = {k: v for k, v in found.items() if v % 8}
    print(f'''"""The bit length each replayed payload had on the wire.

Generated by ``tools/payload_bits.py``; do not edit by hand.

``dsor/data/*.bin`` holds bytes, and a message whose true length is not a multiple of
eight is already padded by the time it is written to a file -- so the length is not
recoverable from the blob and has to be looked up in the capture it came from.

It matters because the frame's length field *is* the boundary the client reads to.
Declaring ``len * 8`` leaves one to seven spare bits at the end, and a multi-command
payload is decoded until its stream runs out, so those bits are read as another
command: "DecodeCommand() invalid command ending in multi command 79!".

{len(found)} of {len(blobs)} blobs were located in the captures, {len(short)} of them
with a sub-byte length. A blob that appears in no capture is absent here and falls
back to ``len * 8``, which is right for a byte-aligned message and the best available
answer for any other.
"""

from __future__ import annotations

#: Blob file name -> its length in bits on the wire.
PAYLOAD_BITS: dict[str, int] = {{''')
    for name in sorted(found):
        mark = "" if found[name] % 8 == 0 else f"  # {len(name)*0 or ''}sub-byte"
        print(f"    {name!r}: {found[name]},{mark}")
    print("}")
    print('''

def bits_for(name: str, body: bytes) -> int:
    """The declared length for the blob called *name*, or ``len * 8``."""
    return PAYLOAD_BITS.get(name, len(body) * 8)''')
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
