"""Generate ``dsor/skills.py`` from the client's own skill templates.

Run from the repository root with the client's database beside it:

    python3 tools/skill_table.py ~/dso/db/db_static.sqlite > dsor/skills.py

Every number a skill needs is in ``_Template_Skill`` — how it picks its victims, how
wide, how far, how hard, and when in the animation the blow lands. Nothing here is
guessed. The wire index is ``rowid - 1``: the client sends 1838 for row 1839,
``angrystrike``, which is how the mapping was confirmed.
"""

import sqlite3
import sys

FIELDS = [
    "Id", "Name", "CharClass", "TargetingType", "SkillType", "Angle", "HitRange", "AttackRange",
    "DamageModifier", "HitFrame", "SkillUnblockFrame", "MotionUnblockFrame",
    "CoolDown", "ResourceCost", "BulletCount", "UseWeaponDPS", "DamageType",
    "UnlockLevel",
]


def main(path: str) -> None:
    db = sqlite3.connect(path)
    rows = db.execute(
        f"SELECT rowid - 1, {', '.join(FIELDS)} FROM _Template_Skill ORDER BY rowid"
    ).fetchall()

    def num(value, default=0.0):
        return default if value is None else round(float(value), 4)

    def whole(value, default=0):
        return default if value is None else int(value)

    def text(value):
        return "" if value is None else str(value)

    print(f'''"""Every skill the client knows, from its own ``_Template_Skill`` table.

Generated by ``tools/skill_table.py``; do not edit by hand.

A skill is not one shape. ``angrystrike`` names a single victim, ``mightyswing`` cuts
a 170 degree arc, ``mighty360`` hits everything within 6.3 units, and each has its own
damage multiplier and its own frame on which the blow lands. Serving them all as one
melee blow against one target is what made the skills unlocked by levelling do
nothing: they arrive as ``SkillCommand`` with no victim named, and a server that only
knows how to hit a named victim has nobody to hit.

The wire index is ``rowid - 1``. Measured: the client sends 1838 for ``angrystrike``,
1839 for ``mightyswing`` and 1842 for ``mighty360``, which are rows 1839, 1840 and
1843.

{len(rows)} skills.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Skill:
    """One row of the client's skill table."""

    wire: int
    id: str
    name: str
    #: The character class the skill belongs to, or "" for the 1875 rows with none --
    #: monster skills, item procs and status-effect carriers. Emitted rather than
    #: inferred from the wire index, because the class blocks overlap: the warrior's
    #: eighteen run 1838 to 1868 and the mage's twenty-four run 1855 to 1879.
    character_class: str
    #: How the skill chooses its victims. ``Actor`` is the one named target; ``Angle``
    #: and ``Cone`` an arc in front; ``Radius`` everything around; ``User`` the caster
    #: alone, which is a buff and damages nobody.
    targeting: str
    kind: str
    #: The arc's full width in degrees, meaningful for ``Angle`` and ``Cone`` only.
    #: ``mighty360`` carries 3.5 here with ``Radius`` targeting, so the field plainly
    #: does not mean degrees for every row -- which is why it is read for those two
    #: targeting types and ignored otherwise.
    angle: float
    #: How far the blow carries, against how close the caster must be to start it.
    hit_range: float
    attack_range: float
    #: What the blow is multiplied by. 1.25 for ``angrystrike``, 1.5 for ``mighty360``.
    damage_modifier: float
    #: The frame the blow lands on, and the frame the animation ends on. Sending the
    #: hit in the same breath as the swing cut the animation to a hundredth of a
    #: second; these are the numbers that space them properly, per skill.
    hit_frame: int
    unblock_frame: int
    motion_unblock_frame: int
    cool_down: float
    resource_cost: float
    bullet_count: int
    uses_weapon_dps: bool
    damage_type: str
    unlock_level: int

    @property
    def area(self) -> bool:
        """Whether the skill strikes more than whatever it is pointed at."""
        return self.targeting in ("Angle", "Cone", "Radius")

    @property
    def harmless(self) -> bool:
        """Whether the skill damages nobody with its own blow.

        Two kinds. A ``User`` skill is cast on the caster: ``warshout``,
        ``frenzyshout``, ``defiance``, ``spikedShield``. And a skill with a zero
        damage modifier carries its whole effect in status effects instead --
        ``battlecry`` debuffs movement speed, resistance and attack speed for five
        seconds; ``earthquake`` lays an aura on the ground that does the damage over
        eight. Neither is modelled here, so the honest thing is to say so in the log
        rather than serve a blow of zero and let it look like a bug.
        """
        return self.targeting == "User" or self.damage_modifier <= 0.0

    @property
    def lands_where_it_ends(self) -> bool:
        """Whether the blow lands somewhere other than where the caster stands.

        A ``Jump``, ``Charge`` or ``ChargeThrough`` travels first and strikes at the
        far end: ``enragingleap`` has an attack range of 10 and a hit range of 2.8,
        so it leaps ten units and hits within under three of where it lands. This
        server measures from where the caster stands, so those two are wrong by up to
        the distance travelled -- generous rather than exact, and recorded here
        because the fix needs the destination, which no message this server receives
        carries.
        """
        return self.kind in ("Jump", "Charge", "ChargeThrough", "Teleport")

    @property
    def arc(self) -> float:
        """The full width of the arc struck, in degrees."""
        if self.targeting in ("Angle", "Cone"):
            return self.angle
        return 360.0


#: Every skill, by wire index.
SKILLS: dict[int, Skill] = {{}}''')

    print()
    print("for _row in [")
    for row in rows:
        (wire, sid, name, char_class, targeting, kind, angle, hit_range,
         attack_range, modifier, hit_frame, unblock, motion, cooldown, cost, bullets,
         weapon_dps, damage_type, unlock) = row
        print(
            f"    ({wire}, {text(sid)!r}, {text(name)!r},"
            f" {text(char_class)!r}, {text(targeting)!r},"
            f" {text(kind)!r}, {num(angle)!r}, {num(hit_range)!r},"
            f" {num(attack_range)!r}, {num(modifier, 1.0)!r}, {whole(hit_frame)},"
            f" {whole(unblock)}, {whole(motion)}, {num(cooldown)!r},"
            f" {num(cost)!r}, {whole(bullets)}, {bool(whole(weapon_dps))},"
            f" {text(damage_type)!r}, {whole(unlock)}),"
        )
    print("]:")
    print("    SKILLS[_row[0]] = Skill(*_row)")
    print("del _row")
    print('''

#: Every skill, by the string id the templates use.
BY_ID: dict[str, Skill] = {s.id: s for s in SKILLS.values()}


def skill(wire: int | None) -> Skill | None:
    """The skill at wire index *wire*, or None if there is no such skill."""
    return None if wire is None else SKILLS.get(wire)


def by_id(name: str) -> Skill | None:
    """The skill with template id *name*, or None."""
    return BY_ID.get(name)


def of_class(name: str) -> list[Skill]:
    """Every skill belonging to character class *name*, by unlock level.

    Eighteen for the warrior, twenty-four for the mage, nineteen for the ranger,
    twenty-one for the dwarf and twenty-six for the steam mechanicus.
    """
    found = [s for s in SKILLS.values() if s.character_class == name]
    return sorted(found, key=lambda s: (s.unlock_level, s.wire))


def wire_of(name: str) -> int | None:
    """The wire index of the skill with template id *name*, or None."""
    found = BY_ID.get(name)
    return None if found is None else found.wire''')


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "db_static.sqlite")
