#!/usr/bin/env python3
"""What the client *calls* each skill, from its own English locale file.

Run as::

    python3 tools/title_table.py ~/dso/DSOClient > dsor/titles.py

Why this exists, plainly: for most of this project the internal ids were matched to
the names on screen by guessing, and the guesses were wrong. "Dragon Hide" is
``frenzyshout``, not ``defiance`` -- ``defiance`` is "Banner of War" -- so every
statement made about Dragon Hide was made about the wrong skill, including a confident
and repeated "it does not heal". ``frenzyshout`` carries
``skill_frenzyshout_buff_lifeleech``, which heals on every hit. The operator said so
three times.

The names come from ``export_win32/language/en/db.skill2.xml`` inside the asset
bundles: ``<item name="<id>Title">`` holds the displayed name for skill ``<id>``.
Nothing is inferred.
"""

from __future__ import annotations

import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))

import bundle  # noqa: E402

LOCALE = "export_win32/language/en/db.skill2.xml"
ITEM = re.compile(r'<item name="([^"]+)"><!\[CDATA\[(.*?)\]\]></item>', re.S)


def titles(client: pathlib.Path) -> dict[str, str]:
    held = bundle.index_all(client)
    if LOCALE not in held:
        raise SystemExit(f"{LOCALE} is in none of the bundles under {client}")
    for name, stored in bundle.read(client / held[LOCALE]):
        if name != LOCALE:
            continue
        text = bundle.unwrap(stored).decode("utf-8-sig")
        found = {}
        for key, value in ITEM.findall(text):
            if key.endswith("Title"):
                found[key[: -len("Title")]] = " ".join(value.split())
        return found
    raise SystemExit("locale file not readable")


def main(argv: list[str]) -> int:
    client = pathlib.Path(
        argv[1] if len(argv) > 1 else pathlib.Path.home() / "dso/DSOClient"
    ).expanduser()
    found = titles(client)
    print(f'''"""What the client calls each skill, in English.

Generated by ``tools/title_table.py``; do not edit by hand.

The mapping is not decoration. Matching internal ids to the names on screen by
guessing is what made this project spend weeks on the wrong skills: "Dragon Hide" is
``frenzyshout`` and ``defiance`` is "Banner of War", so a long and confident argument
that Dragon Hide does not heal was an argument about a different skill entirely --
``frenzyshout`` leeches life on every hit.

Source: ``export_win32/language/en/db.skill2.xml`` in the client's asset bundles.
{len(found)} skills have a displayed name; the rest are internal or event-only.
"""

from __future__ import annotations

#: Internal skill id -> the name the client shows.
TITLES: dict[str, str] = {{''')
    for key in sorted(found):
        print(f"    {key!r}: {found[key]!r},")
    print("}")
    print('''

#: And back, so a name a player uses can be resolved to an id.
BY_TITLE: dict[str, str] = {title.lower(): key for key, title in TITLES.items()}


def title_of(skill_id: str) -> str:
    """The displayed name for *skill_id*, or the id when it has none."""
    return TITLES.get(skill_id, skill_id)


def id_of(title: str) -> str | None:
    """The internal id for a displayed name, matched case-insensitively."""
    return BY_TITLE.get(title.strip().lower())''')
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
