"""What the live service put in a status effect element, per effect.

Generated by tools/effect_tables.py -- do not edit by hand.

Read from 7 captures, of which 0 were dropped as this
emulator's own traffic rather than the live service's. 190 StatusEffectCommand
messages parsed, 0 refused (100.0%).

Each table is split by context, because the fields depend on it: an element that
names a causer -- a debuff someone put on a creature -- carries different values
from a buff an actor put on itself, and one table for both averaged the two into
a value neither of them has.

The four flags are not here. All 402 measured elements with no causer carry
(0,0,0,1) with no exception, so it is a rule in dsor/world.py rather than a table.
"""

from __future__ import annotations

#: How many elements each effect was measured from, both contexts together.
SAMPLES: dict[int, int] = {1270: 46, 1316: 27, 4762: 45, 4763: 45, 5141: 4, 5142: 12, 5143: 4, 5149: 27, 5150: 27, 5152: 12, 5153: 9, 5168: 34, 5169: 34, 5178: 34, 5502: 27, 5739: 7}

#: Field 2, for an effect an actor put on itself.
SECOND: dict[int, int] = {1270: 0, 1316: 25, 4762: 25, 4763: 25, 5141: 25, 5142: 25, 5143: 25, 5149: 25, 5150: 25, 5152: 25, 5153: 0, 5168: 25, 5169: 25, 5178: 25, 5502: 25}

#: Field 2, for one a causer put on someone.
SECOND_CAUSED: dict[int, int] = {1270: 0, 1316: 25, 5142: 25, 5149: 25, 5153: 0, 5168: 25, 5169: 25, 5502: 25, 5739: 25}

#: Field 6.
SIXTH: dict[int, int] = {1270: 100, 1316: 100, 4762: 100, 4763: 100, 5141: 100, 5142: 100, 5143: 100, 5149: 100, 5150: 100, 5152: 100, 5153: 100, 5168: 100, 5169: 100, 5178: 100, 5502: 100}

#: Field 6, caused.
SIXTH_CAUSED: dict[int, int] = {1270: 100, 1316: 100, 5142: 100, 5149: 100, 5153: 100, 5168: 100, 5169: 100, 5502: 100, 5739: 100}

#: The signed byte behind the parameters.
TAIL: dict[int, int] = {1270: -1, 1316: -1, 4762: -1, 4763: -1, 5141: 2, 5142: 2, 5143: 2, 5149: -1, 5150: -1, 5152: -1, 5153: -1, 5168: -1, 5169: -1, 5178: -1, 5502: -1}

#: The same, caused.
TAIL_CAUSED: dict[int, int] = {1270: 0, 1316: -1, 5142: 2, 5149: 2, 5153: 2, 5168: -1, 5169: -1, 5502: 2, 5739: 2}

#: The flag in front of that byte.
MORE: dict[int, int] = {1270: 0, 1316: 0, 4762: 0, 4763: 0, 5141: 1, 5142: 1, 5143: 1, 5149: 0, 5150: 0, 5152: 0, 5153: 0, 5168: 0, 5169: 0, 5178: 0, 5502: 0}

#: The same, caused.
MORE_CAUSED: dict[int, int] = {1270: 1, 1316: 0, 5142: 1, 5149: 1, 5153: 1, 5168: 0, 5169: 0, 5502: 1, 5739: 1}

#: The two float3 behind the parameters. Identical to the bit across five
#: different captures, so it is a constant and not the position it was once
#: taken for. The aura effects are the exception, and they are below.
VECTORS: tuple = (2.1500000953674316, 100.0, 0.7908890843391418, 52.7525520324707, 10.0, -0.27803361415863037)

#: The effects whose vectors differ: an aura carries its radius and a place.
PER_EFFECT_VECTORS: dict[int, tuple] = {
    1270: (235.3040008544922, 46.917999267578125, 0.0, -16.50571060180664, 0.0, 42.69179916381836),
    5153: (235.3040008544922, 46.917999267578125, 0.0, -16.50571060180664, 0.0, 42.69179916381836),
    5502: (5.75, 100.0, 0.7908421754837036, 54.529998779296875, 10.0, 1.4800000190734863),
}


# The two halves above split on whether field 7 is the message's own actor. They are
# read through these, so a caller does not have to know which half an effect landed in.


def second_of(wire: int, default: int = 25) -> int:
    """Field 2 for *wire*."""
    if wire in SECOND_CAUSED:
        return SECOND_CAUSED[wire]
    return SECOND.get(wire, default)


def sixth_of(wire: int, default: int = 100) -> int:
    """Field 6."""
    if wire in SIXTH_CAUSED:
        return SIXTH_CAUSED[wire]
    return SIXTH.get(wire, default)


def tail_of(wire: int, default: int = 2) -> int:
    """The signed byte behind the parameters. -1 means the element carries no vectors."""
    if wire in TAIL:
        return TAIL[wire]
    return TAIL_CAUSED.get(wire, default)


def more_of(wire: int, default: int = 1) -> int:
    """The flag in front of that byte."""
    if wire in MORE:
        return MORE[wire]
    return MORE_CAUSED.get(wire, default)


def vectors_of(wire: int) -> tuple:
    """The two float3, which only an aura's differ in."""
    return PER_EFFECT_VECTORS.get(wire, VECTORS)
