"""Every creature the client knows, from its own ``_Template_Monster`` table.

Generated by ``tools/monster_table.py``; do not edit by hand.

Two of this server's invented numbers are in here plainly, and both were wrong:

  a0001_gen_anderworld_creature   HitPoints 24, damage 1 to 1
  a0001_tutorial_movement_target  HitPoints 2,  damage 0 to 0, Name "hint monster"

Twelve health was served instead of 24, and it came from decoding a recorded blow as
"victim health 0, max 12, damage 11". The caution written beside that reading said
that misreading the field one or two bits late gives 24 -- and 24 is what the client's
own database holds. The mirage warned about was the value actually served.

It also settles an older caution properly. Serving 60 health was read by the client as
a *heal* and drawn as a floating +400, and the conclusion drawn was "serving far more
than 12 is read as a heal". The real rule is narrower and more useful: the client
knows each creature's health from this table, so a figure that disagrees with it is
read as a change to it. Serving the template's own number cannot be misread, however
large it is.

23 creatures, of the table's 7985: those whose id begins with
a0001. Serving another map means
regenerating with its prefix, the way ``dsor/mapdata.py`` is regenerated per map.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import cached_property


@dataclass(frozen=True)
class Monster:
    """One row of the client's monster table."""

    id: str
    #: The shared display name. Several ids share one: the tutorial dungeon's
    #: ordinary creature and its health-globe variant are both "anderworld_creature".
    name: str
    level: int
    hit_points: int
    #: The blow it lands, before its skill's own multiplier. One to one for the
    #: tutorial creature, zero for the practice dummy, five to nine for the champion.
    min_damage: float
    max_damage: float
    armor: float
    #: The raw ``Fire:625;Ice:625;...`` string, parsed on demand by :attr:`resists`.
    resistances: str
    critical_damage_factor: float
    block_damage_reduction: float
    rank_override: int

    @cached_property
    def resists(self) -> dict[str, float]:
        """Resistances by damage type, parsed from the packed string."""
        out: dict[str, float] = {}
        for part in self.resistances.split(";"):
            if ":" not in part:
                continue
            kind, _, value = part.partition(":")
            try:
                out[kind.strip()] = float(value)
            except ValueError:
                continue
        return out

    @property
    def harmless(self) -> bool:
        """Whether it deals no damage at all.

        The tutorial dungeon's movement target is one: two health, no damage, and the
        client calls it a "hint monster". It stands eight units from where a player
        arrives, and serving every creature the same blow meant it hit them
        invisibly.
        """
        return self.max_damage <= 0.0


#: Every creature, by template id.
MONSTERS: dict[str, Monster] = {}

for _row in [
    ('a0001_champion_anderworld_creature_healing', 'anderworld_creature', 1, 24, 1.0, 1.0, 625.0, 'Fire:625;Ice:625;Lightning:625;Poison:625;DarkMagic:1251', 0.0, 0.0, 0),
    ('a0001_champion_anderworld_creature_openexit', 'anderworld_creature', 2, 35, 2.0, 3.0, 632.0, 'Fire:632;Ice:632;Lightning:632;Poison:632;DarkMagic:1265', 0.0, 0.0, 0),
    ('a0001_champion_undead_mage_01', 'undead_mage', 5, 50, 5.0, 9.0, 654.0, 'Fire:654;Ice:654;Lightning:654;Poison:654;DarkMagic:1309', 0.0, 0.0, 0),
    ('a0001_china_champion_andermight_spawner_openexit', 'andermight_spawner', 2, 60, 12.0, 16.0, 80.0, 'Fire:105;Ice:105;Lightning:105;Poison:105;DarkMagic:105', 2.0, 2.0, 0),
    ('a0001_china_champion_anderworld_creature_healing', 'anderworld minion champion', 1, 25, 10.0, 14.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_china_champion_anderworld_creature_openexit', 'anderworld minion champion', 2, 60, 12.0, 16.0, 80.0, 'Fire:105;Ice:105;Lightning:105;Poison:105;DarkMagic:105', 2.0, 0.0, 0),
    ('a0001_china_champion_undead_mage_sequence', 'undead_mage champion', 5, 250, 10.0, 15.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_china_gen_anderworld_creature', 'standard anderworld creature', 1, 5, 4.0, 6.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_china_gen_anderworld_creature_1st_encounter', '1st monster in the game', 1, 5, 4.0, 6.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_china_gen_anderworld_creature_1st_loot', 'anderworld minion 1st loot', 1, 5, 4.0, 6.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_china_gen_anderworld_creature_2nd_loot', 'anderworld minion 2nd loot', 1, 5, 4.0, 6.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_china_gen_anderworld_creature_healthglobe', 'anderworld minion dropping healthglobe', 1, 5, 4.0, 6.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_china_gen_anderworld_creature_q_tutorial', 'anderworld minion', 1, 5, 4.0, 6.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_china_gen_anderworld_minion_01', 'anderworld minion', 2, 9, 5.0, 8.0, 105.0, 'Fire:105;Ice:105;Lightning:105;Poison:105;DarkMagic:105', 2.0, 0.0, 0),
    ('a0001_china_tutorial_movement_target', 'hint monster', 1, 3, 2.0, 3.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:80', 2.0, 0.0, 0),
    ('a0001_gen_anderworld_creature', 'anderworld_creature', 1, 24, 1.0, 1.0, 625.0, 'Fire:625;Ice:625;Lightning:625;Poison:625;DarkMagic:1251', 0.0, 0.0, 0),
    ('a0001_gen_anderworld_creature_1st_encounter', 'anderworld_creature', 1, 24, 1.0, 1.0, 625.0, 'Fire:625;Ice:625;Lightning:625;Poison:625;DarkMagic:1251', 0.0, 0.0, 0),
    ('a0001_gen_anderworld_creature_1st_loot', 'anderworld_creature', 1, 24, 1.0, 1.0, 625.0, 'Fire:625;Ice:625;Lightning:625;Poison:625;DarkMagic:1251', 0.0, 0.0, 0),
    ('a0001_gen_anderworld_creature_2nd_loot', 'anderworld_creature', 1, 24, 1.0, 1.0, 625.0, 'Fire:625;Ice:625;Lightning:625;Poison:625;DarkMagic:1251', 0.0, 0.0, 0),
    ('a0001_gen_anderworld_creature_healthglobe', 'anderworld_creature', 1, 24, 1.0, 1.0, 625.0, 'Fire:625;Ice:625;Lightning:625;Poison:625;DarkMagic:1251', 0.0, 0.0, 0),
    ('a0001_gen_anderworld_creature_q_tutorial_02', 'anderworld_creature', 1, 6, 4.0, 5.0, 80.0, 'Fire:80;Ice:80;Lightning:80;Poison:80;DarkMagic:160', 0.0, 0.0, 0),
    ('a0001_normal_anderworld_minion', 'anderworld minion', 2, 35, 2.0, 3.0, 632.0, 'Fire:632;Ice:632;Lightning:632;Poison:632;DarkMagic:1265', 2.0, 0.0, 0),
    ('a0001_tutorial_movement_target', 'hint monster', 1, 2, 0.0, 0.0, 625.0, 'Fire:625;Ice:625;Lightning:625;Poison:625;DarkMagic:625', 0.0, 0.0, 0),
]:
    MONSTERS[_row[0]] = Monster(*_row)
del _row


def _from_the_database() -> int:
    """Every creature the client knows, not the 23 whose id starts with a0001.

    The generated table above was filtered to one map's prefix, so 7,962 of the
    database's 7,985 monsters were unknown -- and an unknown creature falls back on
    invented health and an invented blow, which is where "12 health" and "every
    creature hits for the same" came from. The client's own database is loaded into
    memory at start now; this widens the table rather than replacing what is in it.

    Returns how many were loaded, or 0 when the file is absent.
    """
    from dsor import database

    found = database.rows(
        "_Template_Monster",
        "Id", "Name", "CharLevel", "HitPoints", "MinDamage", "MaxDamage", "Armor",
        "Resistances", "CriticalDamageFactor", "BlockDamageReduction", "RankOverride",
    )
    if not found:
        return 0

    def text(v):
        return "" if v is None else str(v)

    def number(v):
        return 0.0 if v is None else float(v)

    def whole(v):
        return 0 if v is None else int(v)

    for row in found:
        values = row[1:]
        MONSTERS[text(values[0])] = Monster(
            text(values[0]), text(values[1]), whole(values[2]), whole(values[3]),
            number(values[4]), number(values[5]), number(values[6]), text(values[7]),
            number(values[8]), number(values[9]), whole(values[10]),
        )
    return len(found)


#: How many creatures the table holds: 7985 with the database, 23 without.
LOADED = _from_the_database()



def monster(blueprint: str | None) -> Monster | None:
    """The creature *blueprint* names, or None if the table has no such row.

    ``a0001_normal_anderworld_minion_01`` is one that has none: the map's spawn table
    names it and the monster table does not carry it, so a caller must cope with None
    rather than assume every spawned blueprint is described here.
    """
    return None if blueprint is None else MONSTERS.get(blueprint)
