"""The bit length each replayed payload had on the wire.

Generated by ``tools/payload_bits.py``; do not edit by hand.

``dsor/data/*.bin`` holds bytes, and a message whose true length is not a multiple of
eight is already padded by the time it is written to a file -- so the length is not
recoverable from the blob and has to be looked up in the capture it came from.

It matters because the frame's length field *is* the boundary the client reads to.
Declaring ``len * 8`` leaves one to seven spare bits at the end, and a multi-command
payload is decoded until its stream runs out, so those bits are read as another
command: "DecodeCommand() invalid command ending in multi command 79!".

44 of 62 blobs were located in the captures, 40 of them
with a sub-byte length. A blob that appears in no capture is absent here and falls
back to ``len * 8``, which is right for a byte-aligned message and the best available
answer for any other.
"""

from __future__ import annotations

#: Blob file name -> its length in bits on the wire.
PAYLOAD_BITS: dict[str, int] = {
    'character_chosen_reply.bin': 249,  # sub-byte
    'character_enter_ack.bin': 890,  # sub-byte
    'character_list.bin': 2525,  # sub-byte
    'character_list_tail.bin': 89,  # sub-byte
    'character_release_extra.bin': 41,  # sub-byte
    'entity_snapshot.bin': 888,
    'hit_08000100.bin': 3201,  # sub-byte
    'hit_0a000100.bin': 3201,  # sub-byte
    'hit_0b000100.bin': 3201,  # sub-byte
    'hit_0f000100.bin': 3201,  # sub-byte
    'hit_10000100.bin': 1848,
    'hit_12000100.bin': 4356,  # sub-byte
    'incoming_hit.bin': 1307,  # sub-byte
    'item_info_unprompted.bin': 1387,  # sub-byte
    'item_pickup_batch.bin': 3510,  # sub-byte
    'leave_08000100.bin': 1038,  # sub-byte
    'leave_0a000100.bin': 886,  # sub-byte
    'leave_0b000100.bin': 886,  # sub-byte
    'leave_0f000100.bin': 886,  # sub-byte
    'leave_10000100.bin': 886,  # sub-byte
    'location_effect_003c.bin': 2722,  # sub-byte
    'location_effect_003d.bin': 7246,  # sub-byte
    'location_effect_003e.bin': 8467,  # sub-byte
    'monster_a0003_gen_thing_swamp.bin': 1312,
    'monster_a0003_swamp_spawner.bin': 1292,  # sub-byte
    'release_010c_a.bin': 88,
    'tick_state.bin': 766,  # sub-byte
    'vicinity_08000100.bin': 886,  # sub-byte
    'vicinity_0a000100.bin': 886,  # sub-byte
    'vicinity_0b000100.bin': 886,  # sub-byte
    'vicinity_0f000100.bin': 886,  # sub-byte
    'vicinity_10000100.bin': 886,  # sub-byte
    'vicinity_12000100.bin': 886,  # sub-byte
    'zone_extra.bin': 1450,  # sub-byte
    'zone_ready.bin': 313,  # sub-byte
    'zone_trigger_00.bin': 5143,  # sub-byte
    'zone_trigger_01.bin': 3285,  # sub-byte
    'zone_trigger_02.bin': 886,  # sub-byte
    'zone_trigger_03.bin': 3285,  # sub-byte
    'zone_trigger_04.bin': 3285,  # sub-byte
    'zone_trigger_05.bin': 886,  # sub-byte
    'zone_trigger_06.bin': 3173,  # sub-byte
    'zone_trigger_07.bin': 3173,  # sub-byte
    'zone_trigger_08.bin': 3245,  # sub-byte
}


def bits_for(name: str, body: bytes) -> int:
    """The declared length for the blob called *name*, or ``len * 8``."""
    return PAYLOAD_BITS.get(name, len(body) * 8)
