"""What the client calls each skill, in English.

Generated by ``tools/title_table.py``; do not edit by hand.

The mapping is not decoration. Matching internal ids to the names on screen by
guessing is what made this project spend weeks on the wrong skills: "Dragon Hide" is
``frenzyshout`` and ``defiance`` is "Banner of War", so a long and confident argument
that Dragon Hide does not heal was an argument about a different skill entirely --
``frenzyshout`` leeches life on every hit.

Source: ``export_win32/language/en/db.skill2.xml`` in the client's asset bundles.
75 skills have a displayed name; the rest are internal or event-only.
"""

from __future__ import annotations

#: Internal skill id -> the name the client shows.
TITLES: dict[str, str] = {
    'Flamethrower': 'Flamethrower',
    'Grenade': 'Bomb',
    'HeavyShot': 'Heavy Shot',
    'HoverJump': 'Rocket Pack',
    'IronDwarf': 'Iron Dwarf',
    'IronDwarfEnd': 'Stop Iron Dwarf',
    'IronDwarfMovementSkill': 'Iron Pounce',
    'IronDwarfPrimarySkill': 'Iron Fist',
    'IronFlamethrower': 'Flamethrower',
    'JackInTheBox': 'Dwarf-in-the-Box',
    'Mine': 'Mine',
    'PositionBombShot': 'C14 Micro-Rocket',
    'ShrapnelShot': 'Shrapnel Shot',
    'SimpleShot': 'Quick Shot',
    'SimpleShot_Chimera': 'Chimera Shot',
    'SteamConductor': 'Steam Conductor',
    'ToxicExplosion': 'Toxic Explosion',
    'Trail': 'Oil Slick',
    'TurretCombat': 'Mechanical Turret',
    'TurretCoveringFire': 'Tactical Turret',
    'TurretMachineGun': 'Machine Gun Turret',
    'TurretTesla': 'Tesla Turret',
    'adrenalin': 'Adrenaline',
    'angrystrike': 'Rage Attack',
    'arcanecharge': 'Arcane Charge',
    'arcanemanifestation': 'Guardian',
    'arcanetorrent': 'Destruction',
    'arcanevortex': 'Singularity',
    'balllightning': 'Ball Lightning',
    'battlecry': 'Outburst',
    'birdofprey': 'Bird of Prey',
    'bloody360': 'Bloody Wild Swing',
    'bloody360_Chimera': 'Chimera Bloody Wild Swing',
    'chainlightning': 'Chain Lightning',
    'defiance': 'Banner of War',
    'earthquake': 'Fury of the Dragon',
    'enragingleap': 'Rage Jump',
    'explosiveshot': 'Explosive Arrow',
    'fireball': 'Fireball',
    'firemanifestation': 'Guardian of Flames',
    'firetorrent': 'Fire Blast',
    'frenzyshout': 'Dragon Hide',
    'frostnova': 'Frost Nova',
    'frostwind': 'Frost Wind',
    'frozenorb': 'Frozen Sphere',
    'hornetcloud': 'Hornet Cloud',
    'iceball': 'Ice Missile',
    'icecharge': 'Frost Charge',
    'jump': 'Dive',
    'laceratingstrike': 'Iron Brow',
    'lightningstrike': 'Lightning Strike',
    'magicmissile': 'Magic Missile',
    'markshot': 'Hunting Arrow',
    'meteor': 'Meteor',
    'mighty360': 'Mighty Wild Swing',
    'mightybash': 'Smash',
    'mightyshot': 'Precise Shot',
    'mightystab': 'Deadly Blow',
    'mightyswing': 'Rageful Swing',
    'mindcontrol': 'Mind Control',
    'multishot': 'Scatter Shot',
    'multishot_Chimera': 'Chimera Scatter',
    'packofwolves': 'Wild Pack',
    'seismicslam': 'Ground Breaker',
    'spikedShield': 'Spike Shield',
    'stab': 'Death Sweep',
    'stuncharge': 'Charge',
    'stunshot': 'Net',
    'summontree': 'Tree of Life',
    'teleport': 'Teleport',
    'thorntrail': 'Thicket of Thorns',
    'trap': 'Hunting Trap',
    'true_earthquake': 'True Dragon Fury',
    'warshout': 'Furious Battle Cry',
    'whirlwind': 'Blade Dance',
}


#: And back, so a name a player uses can be resolved to an id.
BY_TITLE: dict[str, str] = {title.lower(): key for key, title in TITLES.items()}


def title_of(skill_id: str) -> str:
    """The displayed name for *skill_id*, or the id when it has none."""
    return TITLES.get(skill_id, skill_id)


def id_of(title: str) -> str | None:
    """The internal id for a displayed name, matched case-insensitively."""
    return BY_TITLE.get(title.strip().lower())
